import { Button, Container, Text, Video, Input, Image, Anchor } from 'display/raw-components';
import {
  CraftButton,
  CraftContainer,
  CraftText,
  CraftVideo,
  CraftInput,
  CraftImage,
  CraftAnchor,
} from 'display/selectors';

export const MenuTemplateConfig = [
  {
    raw: {
      type: Container,
      overwriteProps: {
        background: { r: '255', g: '255', b: '255', a: '1' },
        flexDirection: 'row',
        justifyContent: 'center',
        width: '100%',
        height: 'auto',
        padding: ['4', '4', '4', '4'],
        margin: ['0', '0', '4', '0'],
        className: 'cursor-move',
      },
      children: [
        {
          type: Anchor,
          overwriteProps: {
            color: { r: '0', g: '0', b: '0', a: '1' },
            background: { r: 0, g: 0, b: 0, a: 0 },
            fontSize: '12',
            width: 'auto',
            fontWeight: '400',
            anchorStyle: 'outline',
            padding: ['4', '4', '4', '4'],
            text: 'Home',
            className: 'cursor-move',
          },
          children: [],
        },
        {
          type: Anchor,
          overwriteProps: {
            color: { r: '0', g: '0', b: '0', a: '1' },
            background: { r: 0, g: 0, b: 0, a: 0 },
            fontSize: '12',
            width: 'auto',
            fontWeight: '400',
            anchorStyle: 'outline',
            padding: ['4', '4', '4', '4'],
            text: 'About',
            className: 'cursor-move',
          },
          children: [],
        },
        {
          type: Anchor,
          overwriteProps: {
            color: { r: '0', g: '0', b: '0', a: '1' },
            background: { r: 0, g: 0, b: 0, a: 0 },
            fontSize: '12',
            width: 'auto',
            fontWeight: '400',
            anchorStyle: 'outline',
            padding: ['4', '4', '4', '4'],
            text: 'Products',
            className: 'cursor-move',
          },
          children: [],
        },
        {
          type: Anchor,
          overwriteProps: {
            color: { r: '0', g: '0', b: '0', a: '1' },
            background: { r: 0, g: 0, b: 0, a: 0 },
            fontSize: '12',
            width: 'auto',
            fontWeight: '400',
            anchorStyle: 'outline',
            padding: ['4', '4', '4', '4'],
            text: 'Personal',
            className: 'cursor-move',
          },
          children: [],
        },
      ],
    },
    craft: {
      type: CraftContainer,
      overwriteProps: {
        background: { r: '255', g: '255', b: '255', a: '1' },
        flexDirection: 'row',
        justifyContent: 'center',
        width: '100%',
        height: 'auto',
        padding: ['16', '16', '16', '16'],
        margin: ['0', '0', '16', '0'],
      },
      children: [
        {
          type: CraftAnchor,
          overwriteProps: {
            color: { r: '0', g: '0', b: '0', a: '1' },
            background: { r: 0, g: 0, b: 0, a: 0 },
            fontSize: '16',
            width: 'auto',
            fontWeight: '400',
            anchorStyle: 'outline',
            text: 'Home',
          },
          children: [],
        },
        {
          type: CraftAnchor,
          overwriteProps: {
            color: { r: '0', g: '0', b: '0', a: '1' },
            background: { r: 0, g: 0, b: 0, a: 0 },
            fontSize: '16',
            width: 'auto',
            fontWeight: '400',
            anchorStyle: 'outline',
            text: 'About',
          },
          children: [],
        },
        {
          type: CraftAnchor,
          overwriteProps: {
            color: { r: '0', g: '0', b: '0', a: '1' },
            background: { r: 0, g: 0, b: 0, a: 0 },
            fontSize: '16',
            width: 'auto',
            fontWeight: '400',
            anchorStyle: 'outline',
            text: 'Products',
          },
          children: [],
        },
        {
          type: CraftAnchor,
          overwriteProps: {
            color: { r: '0', g: '0', b: '0', a: '1' },
            background: { r: 0, g: 0, b: 0, a: 0 },
            fontSize: '16',
            width: 'auto',
            fontWeight: '400',
            anchorStyle: 'outline',
            text: 'Personal',
          },
          children: [],
        },
      ],
    },
  },
  {
    raw: {
      type: Container,
      overwriteProps: {
        background: { r: '255', g: '255', b: '255', a: '1' },
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        height: 'auto',
        padding: ['0', '0', '0', '0'],
        margin: ['0', '0', '0', '0'],
        className: 'cursor-move',
      },
      children: [
        {
          type: Container,
          overwriteProps: {
            background: { r: '255', g: '255', b: '255', a: '1' },
            flexDirection: 'row',
            justifyContent: 'flex-start',
            width: '100%',
            height: 'auto',
            padding: ['4', '4', '4', '4'],
            margin: ['0', '0', '4', '0'],
          },
          children: [
            {
              type: Anchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '10',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'Home',
                className: 'cursor-move',
              },
              children: [],
            },
            {
              type: Anchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '10',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'About',
                className: 'cursor-move',
              },
              children: [],
            },
            {
              type: Anchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '10',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'Products',
                className: 'cursor-move',
              },
              children: [],
            },
            {
              type: Anchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '10',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'Personal',
                className: 'cursor-move',
              },
              children: [],
            },
          ],
        },
        {
          type: Container,
          overwriteProps: {
            background: { r: '255', g: '255', b: '255', a: '1' },
            flexDirection: 'row',
            justifyContent: 'flex-end',
            width: '100%',
            height: 'auto',
            padding: ['4', '4', '4', '4'],
            margin: ['0', '0', '4', '0'],
          },
          children: [
            {
              type: Button,
              overwriteProps: {
                color: { r: '255', g: '255', b: '255', a: '1' },
                background: { r: '9', g: '35', b: '163', a: '1' },
                fontSize: '10',
                width: '40px',
                fontWeight: '400',
                text: 'Login',
                padding: ['4', '4', '4', '4'],
                margin: ['5', '4', '5', '0'],
                className: 'cursor-move',
              },
            },
            {
              type: Button,
              overwriteProps: {
                color: { r: '255', g: '255', b: '255', a: '1' },
                background: { r: '197', g: '8', b: '41', a: '1' },
                fontSize: '10',
                width: '60px',
                fontWeight: '400',
                text: 'Register',
                padding: ['4', '4', '4', '4'],
                className: 'cursor-move',
              },
            },
          ],
        },
      ],
    },
    craft: {
      type: CraftContainer,
      overwriteProps: {
        background: { r: '255', g: '255', b: '255', a: '1' },
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        height: 'auto',
        padding: ['0', '0', '0', '0'],
        margin: ['0', '0', '0', '0'],
      },
      children: [
        {
          type: CraftContainer,
          overwriteProps: {
            background: { r: '255', g: '255', b: '255', a: '1' },
            flexDirection: 'row',
            justifyContent: 'flex-start',
            width: '100%',
            height: 'auto',
            padding: ['4', '4', '4', '4'],
            margin: ['0', '0', '4', '0'],
          },
          children: [
            {
              type: CraftAnchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '14',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'Home',
              },
              children: [],
            },
            {
              type: CraftAnchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '14',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'About',
              },
              children: [],
            },
            {
              type: CraftAnchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '14',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'Products',
              },
              children: [],
            },
            {
              type: CraftAnchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '14',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'Personal',
              },
              children: [],
            },
          ],
        },
        {
          type: CraftContainer,
          overwriteProps: {
            background: { r: '255', g: '255', b: '255', a: '1' },
            flexDirection: 'row',
            justifyContent: 'flex-end',
            width: '30%',
            height: 'auto',
            padding: ['4', '4', '4', '4'],
            margin: ['0', '0', '4', '0'],
          },
          children: [
            {
              type: CraftButton,
              overwriteProps: {
                color: { r: '255', g: '255', b: '255', a: '1' },
                background: { r: '9', g: '35', b: '163', a: '1' },
                fontSize: '14',
                width: '50%',
                fontWeight: '400',
                text: 'Login',
                padding: ['4', '4', '4', '4'],
                margin: ['5', '4', '5', '0'],
              },
            },
            {
              type: CraftButton,
              overwriteProps: {
                color: { r: '255', g: '255', b: '255', a: '1' },
                background: { r: '197', g: '8', b: '41', a: '1' },
                fontSize: '14',
                width: '50%',
                fontWeight: '400',
                text: 'Register',
                padding: ['4', '4', '4', '4'],
              },
            },
          ],
        },
      ],
    },
  },
  {
    raw: {
      type: Container,
      overwriteProps: {
        background: { r: '255', g: '255', b: '255', a: '1' },
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        height: 'auto',
        padding: ['0', '0', '0', '0'],
        margin: ['0', '0', '0', '0'],
        className: 'cursor-move',
      },
      children: [
        {
          type: Image,
          overwriteProps: {
            height: 'auto',
            width: 'auto',
            className: 'cursor-move',
            src: 'https://www.ctda.hcmus.edu.vn/wp-content/uploads/2022/03/FIT-logo_dat_kem_voi_logo_truong.png',
            objectFit: 'contain',
          },
        },
        {
          type: Container,
          overwriteProps: {
            background: { r: '255', g: '255', b: '255', a: '1' },
            flexDirection: 'row',
            justifyContent: 'flex-start',
            width: '100%',
            height: 'auto',
            padding: ['4', '4', '4', '4'],
            margin: ['0', '0', '4', '0'],
          },
          children: [
            {
              type: Anchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '10',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'Home',
                className: 'cursor-move',
              },
              children: [],
            },
            {
              type: Anchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '10',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'About',
                className: 'cursor-move',
              },
              children: [],
            },
            {
              type: Anchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '10',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'Products',
                className: 'cursor-move',
              },
              children: [],
            },
            {
              type: Anchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '10',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'Personal',
                className: 'cursor-move',
              },
              children: [],
            },
          ],
        },
        {
          type: Container,
          overwriteProps: {
            background: { r: '255', g: '255', b: '255', a: '1' },
            flexDirection: 'row',
            justifyContent: 'flex-start',
            width: 'auto',
            height: 'auto',
            padding: ['4', '4', '4', '4'],
            margin: ['0', '0', '4', '0'],
          },
          children: [
            {
              type: Button,
              overwriteProps: {
                color: { r: '255', g: '255', b: '255', a: '1' },
                background: { r: '9', g: '35', b: '163', a: '1' },
                fontSize: '10',
                width: '40px',
                fontWeight: '400',
                text: 'Login',
                padding: ['4', '4', '4', '4'],
                margin: ['5', '4', '5', '0'],
                className: 'cursor-move',
              },
            },
          ],
        },
      ],
    },
    craft: {
      type: CraftContainer,
      overwriteProps: {
        background: { r: '255', g: '255', b: '255', a: '1' },
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        height: 'auto',
        padding: ['0', '0', '0', '0'],
        margin: ['0', '0', '0', '0'],
      },
      children: [
        {
          type: CraftImage,
          overwriteProps: {
            height: '60px',
            width: '120px',
            className: 'cursor-move',
            src: 'https://www.ctda.hcmus.edu.vn/wp-content/uploads/2022/03/FIT-logo_dat_kem_voi_logo_truong.png',
            objectFit: 'contain',
          },
        },
        {
          type: CraftContainer,
          overwriteProps: {
            background: { r: '255', g: '255', b: '255', a: '1' },
            flexDirection: 'row',
            justifyContent: 'flex-start',
            width: 'auto',
            height: 'auto',
            padding: ['16', '16', '16', '16'],
            margin: ['0', '0', '0', '16'],
          },
          children: [
            {
              type: CraftAnchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '14',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'Home',
              },
              children: [],
            },
            {
              type: CraftAnchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '14',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'About',
              },
              children: [],
            },
            {
              type: CraftAnchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '14',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'Products',
              },
              children: [],
            },
            {
              type: CraftAnchor,
              overwriteProps: {
                color: { r: '0', g: '0', b: '0', a: '1' },
                background: { r: 0, g: 0, b: 0, a: 0 },
                fontSize: '14',
                width: 'auto',
                fontWeight: '400',
                anchorStyle: 'outline',
                padding: ['4', '4', '4', '4'],
                text: 'Personal',
              },
              children: [],
            },
          ],
        },
        {
          type: CraftContainer,
          overwriteProps: {
            background: { r: '255', g: '255', b: '255', a: '1' },
            flexDirection: 'row',
            justifyContent: 'flex-start',
            width: 'auto',
            height: 'auto',
            padding: ['4', '4', '4', '4'],
            margin: ['0', '0', '4', '0'],
          },
          children: [
            {
              type: CraftButton,
              overwriteProps: {
                color: { r: '255', g: '255', b: '255', a: '1' },
                background: { r: '9', g: '35', b: '163', a: '1' },
                fontSize: '14',
                fontWeight: '400',
                text: 'Login',
                padding: ['4', '4', '4', '4'],
                margin: ['5', '4', '5', '0'],
              },
            },
          ],
        },
      ],
    },
  },
];
